[project]
name = "nowcastnhsn"
version = "0.1.0"
description = "python deps for nowcastnhsn"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cfa-dataops",
]

[tool.uv.sources]
cfa-dataops = { git = "https://github.com/CDCgov/cfa-dataops" }
